baseURL = "https://infratographer.com/"
languageCode = "en-us"
title = "Infratographer"

disableKinds = ["home", "section", "taxonomy", "term", "sitemap", "RSS" ]
ignoreErrors = ["error-disable-taxonomy"]

publishDir = "docs"

[Permalinks]
	code = "/:filename/"
